name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run tests
        run: python tests.py  

      - name: Zip repository content
        run: zip -r webcounter.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: webcounter-artifact
          path: webcounter.zip
